backend:
  name: git-gateway
  branch: main

media_folder: "gallery"
public_folder: "/gallery"

collections:
  - name: "trabajos"
    label: "Trabajos de Tapicería"
    folder: "src/gallery"
    create: true
    slug: "{{id}}"
    extension: "json"
    fields:
      - { label: "Nombre del Modelo", name: "title", widget: "string" }
      - { label: "Identificador (ID único, en minúsculas, sin espacios)", name: "id", widget: "string" }
      - label: "Imágenes del Trabajo"
        name: "images"
        widget: "list"
        summary: "{{fields.image}}"
        field: { label: "Imagen", name: "image", widget: "image" }
        
